export default [
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/us.png'),
    code: 'US',
    name: 'United States',
    inputMask: '[000] [000] [0000]',
    config: [
      '907',
      '205',
      '251',
      '256',
      '334',
      '479',
      '501',
      '870',
      '480',
      '520',
      '602',
      '623',
      '928',
      '209',
      '213',
      '310',
      '323',
      '408',
      '415',
      '510',
      '530',
      '559',
      '562',
      '619',
      '626',
      '650',
      '661',
      '707',
      '714',
      '760',
      '805',
      '818',
      '831',
      '858',
      '909',
      '916',
      '925',
      '949',
      '951',
      '303',
      '719',
      '970',
      '203',
      '860',
      '202',
      '302',
      '239',
      '305',
      '321',
      '352',
      '386',
      '407',
      '561',
      '727',
      '772',
      '813',
      '850',
      '863',
      '904',
      '941',
      '954',
      '229',
      '404',
      '478',
      '706',
      '770',
      '912',
      '808',
      '319',
      '515',
      '563',
      '641',
      '712',
      '208',
      '217',
      '309',
      '312',
      '618',
      '630',
      '708',
      '773',
      '815',
      '847',
      '219',
      '260',
      '317',
      '574',
      '765',
      '812',
      '316',
      '620',
      '785',
      '913',
      '270',
      '502',
      '606',
      '859',
      '225',
      '318',
      '337',
      '504',
      '985',
      '413',
      '508',
      '617',
      '781',
      '978',
      '301',
      '410',
      '207',
      '231',
      '248',
      '269',
      '313',
      '517',
      '586',
      '616',
      '734',
      '810',
      '906',
      '989',
      '218',
      '320',
      '507',
      '612',
      '651',
      '763',
      '952',
      '314',
      '417',
      '573',
      '636',
      '660',
      '816',
      '228',
      '601',
      '662',
      '406',
      '252',
      '336',
      '704',
      '828',
      '910',
      '919',
      '701',
      '308',
      '402',
      '603',
      '201',
      '609',
      '732',
      '856',
      '908',
      '973',
      '505',
      '575',
      '702',
      '775',
      '212',
      '315',
      '516',
      '518',
      '585',
      '607',
      '631',
      '716',
      '718',
      '845',
      '914',
      '216',
      '330',
      '419',
      '440',
      '513',
      '614',
      '740',
      '937',
      '405',
      '580',
      '918',
      '503',
      '541',
      '215',
      '412',
      '570',
      '610',
      '717',
      '724',
      '814',
      '401',
      '803',
      '843',
      '864',
      '605',
      '423',
      '615',
      '731',
      '865',
      '901',
      '931',
      '210',
      '214',
      '254',
      '281',
      '325',
      '361',
      '409',
      '432',
      '512',
      '713',
      '806',
      '817',
      '830',
      '903',
      '915',
      '936',
      '940',
      '956',
      '972',
      '979',
      '435',
      '801',
      '276',
      '434',
      '540',
      '703',
      '757',
      '804',
      '802',
      '206',
      '253',
      '360',
      '425',
      '509',
      '262',
      '414',
      '608',
      '715',
      '920',
      '304',
      '307',
    ],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/ca.png'),
    code: 'CA',
    name: 'Canada',
    inputMask: '[000] [000] [0000]',
    config: [
      '204',
      '226',
      '236',
      '249',
      '250',
      '289',
      '306',
      '343',
      '365',
      '387',
      '403',
      '416',
      '418',
      '431',
      '437',
      '438',
      '450',
      '506',
      '514',
      '519',
      '548',
      '579',
      '581',
      '587',
      '604',
      '613',
      '639',
      '647',
      '672',
      '705',
      '709',
      '742',
      '778',
      '780',
      '782',
      '807',
      '819',
      '825',
      '867',
      '873',
      '902',
      '905',
    ],
  },
  {
    dialCode: '+376',
    uri: require('views/assets/images/flags/ad.png'),
    code: 'AD',
    name: 'Andorra',
    inputMask: '[000] [000]',
    config: [],
  },
  {
    dialCode: '+971',
    uri: require('views/assets/images/flags/ae.png'),
    code: 'AE',
    name: 'United Arab Emirates',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+93',
    uri: require('views/assets/images/flags/af.png'),
    code: 'AF',
    name: 'Afghanistan',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/ag.png'),
    code: 'AG',
    name: 'Antigua and Barbuda',
    inputMask: '[000] [000] [0000]',
    config: ['268'],
  },
  {
    dialCode: '+355',
    uri: require('views/assets/images/flags/al.png'),
    code: 'AL',
    name: 'Albania',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+374',
    uri: require('views/assets/images/flags/am.png'),
    code: 'AM',
    name: 'Armenia',
    inputMask: '[00] [000000]',
    config: [],
  },
  {
    dialCode: '+244',
    uri: require('views/assets/images/flags/ao.png'),
    code: 'AO',
    name: 'Angola',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+54',
    uri: require('views/assets/images/flags/ar.png'),
    code: 'AR',
    name: 'Argentina',
    inputMask: '[0] [00] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+43',
    uri: require('views/assets/images/flags/at.png'),
    code: 'AT',
    name: 'Austria',
    inputMask: '[000] [000000]',
    config: [],
  },
  {
    dialCode: '+61',
    uri: require('views/assets/images/flags/au.png'),
    code: 'AU',
    name: 'Australia',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+297',
    uri: require('views/assets/images/flags/aw.png'),
    code: 'AW',
    name: 'Aruba',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+994',
    uri: require('views/assets/images/flags/az.png'),
    code: 'AZ',
    name: 'Azerbaijan',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+387',
    uri: require('views/assets/images/flags/ba.png'),
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/bb.png'),
    code: 'BB',
    name: 'Barbados',
    inputMask: '[000] [000] [0000]',
    config: ['246'],
  },
  {
    dialCode: '+880',
    uri: require('views/assets/images/flags/bd.png'),
    code: 'BD',
    name: 'Bangladesh',
    inputMask: '[0000] [000000]',
    config: [],
  },
  {
    dialCode: '+32',
    uri: require('views/assets/images/flags/be.png'),
    code: 'BE',
    name: 'Belgium',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+226',
    uri: require('views/assets/images/flags/bf.png'),
    code: 'BF',
    name: 'Burkina Faso',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+359',
    uri: require('views/assets/images/flags/bg.png'),
    code: 'BG',
    name: 'Bulgaria',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+973',
    uri: require('views/assets/images/flags/bh.png'),
    code: 'BH',
    name: 'Bahrain',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+257',
    uri: require('views/assets/images/flags/bi.png'),
    code: 'BI',
    name: 'Burundi',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+229',
    uri: require('views/assets/images/flags/bj.png'),
    code: 'BJ',
    name: 'Benin',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+673',
    uri: require('views/assets/images/flags/bn.png'),
    code: 'BN',
    name: 'Brunei',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+591',
    uri: require('views/assets/images/flags/bo.png'),
    code: 'BO',
    name: 'Bolivia',
    inputMask: '[00000000]',
    config: [],
  },
  {
    dialCode: '+599',
    uri: require('views/assets/images/flags/bq.png'),
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    inputMask: '[000] [0000]',
    config: ['715'],
  },
  {
    dialCode: '+55',
    uri: require('views/assets/images/flags/br.png'),
    code: 'BR',
    name: 'Brazil',
    inputMask: '[00] [00000] [0000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/bs.png'),
    code: 'BS',
    name: 'Bahamas',
    inputMask: '[000] [000] [0000]',
    config: ['242'],
  },
  {
    dialCode: '+975',
    uri: require('views/assets/images/flags/bt.png'),
    code: 'BT',
    name: 'Bhutan',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+267',
    uri: require('views/assets/images/flags/bw.png'),
    code: 'BW',
    name: 'Botswana',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+375',
    uri: require('views/assets/images/flags/by.png'),
    code: 'BY',
    name: 'Belarus',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+501',
    uri: require('views/assets/images/flags/bz.png'),
    code: 'BZ',
    name: 'Belize',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+243',
    uri: require('views/assets/images/flags/cd.png'),
    code: 'CD',
    name: 'Congo, Democratic Republic of the',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+236',
    uri: require('views/assets/images/flags/cf.png'),
    code: 'CF',
    name: 'Central African Republic',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+242',
    uri: require('views/assets/images/flags/cg.png'),
    code: 'CG',
    name: 'Congo',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+41',
    uri: require('views/assets/images/flags/ch.png'),
    code: 'CH',
    name: 'Switzerland',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+225',
    uri: require('views/assets/images/flags/ci.png'),
    code: 'CI',
    name: "Côte d'Ivoire",
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+56',
    uri: require('views/assets/images/flags/cl.png'),
    code: 'CL',
    name: 'Chile',
    inputMask: '[0] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+237',
    uri: require('views/assets/images/flags/cm.png'),
    code: 'CM',
    name: 'Cameroon',
    inputMask: '[0] [00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+86',
    uri: require('views/assets/images/flags/cn.png'),
    code: 'CN',
    name: 'China',
    inputMask: '[000] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+57',
    uri: require('views/assets/images/flags/co.png'),
    code: 'CO',
    name: 'Colombia',
    inputMask: '[000] [0000000]',
    config: [],
  },
  {
    dialCode: '+506',
    uri: require('views/assets/images/flags/cr.png'),
    code: 'CR',
    name: 'Costa Rica',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+53',
    uri: require('views/assets/images/flags/cu.png'),
    code: 'CU',
    name: 'Cuba',
    inputMask: '[0] [0000000]',
    config: [],
  },
  {
    dialCode: '+238',
    uri: require('views/assets/images/flags/cv.png'),
    code: 'CV',
    name: 'Cape Verde',
    inputMask: '[000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+599',
    uri: require('views/assets/images/flags/cw.png'),
    code: 'CW',
    name: 'Curaçao',
    inputMask: '[0] [000] [0000]',
    config: ['9'],
  },
  {
    dialCode: '+357',
    uri: require('views/assets/images/flags/cy.png'),
    code: 'CY',
    name: 'Cyprus',
    inputMask: '[00] [000000]',
    config: [],
  },
  {
    dialCode: '+420',
    uri: require('views/assets/images/flags/cz.png'),
    code: 'CZ',
    name: 'Czech Republic',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+49',
    uri: require('views/assets/images/flags/de.png'),
    code: 'DE',
    name: 'Germany',
    inputMask: '[0000] [0000000]',
    config: [],
  },
  {
    dialCode: '+253',
    uri: require('views/assets/images/flags/dj.png'),
    code: 'DJ',
    name: 'Djibouti',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+45',
    uri: require('views/assets/images/flags/dk.png'),
    code: 'DK',
    name: 'Denmark',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/dm.png'),
    code: 'DM',
    name: 'Dominica',
    inputMask: '[000] [000] [0000]',
    config: ['767'],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/do.png'),
    code: 'DO',
    name: 'Dominican Republic',
    inputMask: '[000] [000] [0000]',
    config: ['809', '829', '849'],
  },
  {
    dialCode: '+213',
    uri: require('views/assets/images/flags/dz.png'),
    code: 'DZ',
    name: 'Algeria',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+593',
    uri: require('views/assets/images/flags/ec.png'),
    code: 'EC',
    name: 'Ecuador',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+372',
    uri: require('views/assets/images/flags/ee.png'),
    code: 'EE',
    name: 'Estonia',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+20',
    uri: require('views/assets/images/flags/eg.png'),
    code: 'EG',
    name: 'Egypt',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+291',
    uri: require('views/assets/images/flags/er.png'),
    code: 'ER',
    name: 'Eritrea',
    inputMask: '[0] [000] [000]',
    config: [],
  },
  {
    dialCode: '+34',
    uri: require('views/assets/images/flags/es.png'),
    code: 'ES',
    name: 'Spain',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+251',
    uri: require('views/assets/images/flags/et.png'),
    code: 'ET',
    name: 'Ethiopia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+358',
    uri: require('views/assets/images/flags/fi.png'),
    code: 'FI',
    name: 'Finland',
    inputMask: '[00] [0000000]',
    config: [],
  },
  {
    dialCode: '+679',
    uri: require('views/assets/images/flags/fj.png'),
    code: 'FJ',
    name: 'Fiji',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+691',
    uri: require('views/assets/images/flags/fm.png'),
    code: 'FM',
    name: 'Micronesia, Federated States of',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+33',
    uri: require('views/assets/images/flags/fr.png'),
    code: 'FR',
    name: 'France',
    inputMask: '[0] [00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+241',
    uri: require('views/assets/images/flags/ga.png'),
    code: 'GA',
    name: 'Gabon',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+44',
    uri: require('views/assets/images/flags/gb.png'),
    code: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    inputMask: '[0000] [000000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/gd.png'),
    code: 'GD',
    name: 'Grenada',
    inputMask: '[000] [000] [0000]',
    config: ['473'],
  },
  {
    dialCode: '+995',
    uri: require('views/assets/images/flags/ge.png'),
    code: 'GE',
    name: 'Georgia',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+594',
    uri: require('views/assets/images/flags/gf.png'),
    code: 'GF',
    name: 'French Guiana',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+233',
    uri: require('views/assets/images/flags/gh.png'),
    code: 'GH',
    name: 'Ghana',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+220',
    uri: require('views/assets/images/flags/gm.png'),
    code: 'GM',
    name: 'Gambia',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+224',
    uri: require('views/assets/images/flags/gn.png'),
    code: 'GN',
    name: 'Guinea',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+590',
    uri: require('views/assets/images/flags/gp.png'),
    code: 'GP',
    name: 'Guadeloupe',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+240',
    uri: require('views/assets/images/flags/gq.png'),
    code: 'GQ',
    name: 'Equatorial Guinea',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+30',
    uri: require('views/assets/images/flags/gr.png'),
    code: 'GR',
    name: 'Greece',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+502',
    uri: require('views/assets/images/flags/gt.png'),
    code: 'GT',
    name: 'Guatemala',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/gu.png'),
    code: 'GU',
    name: 'Guam',
    inputMask: '[000] [000] [0000]',
    config: ['671'],
  },
  {
    dialCode: '+245',
    uri: require('views/assets/images/flags/gw.png'),
    code: 'GW',
    name: 'Guinea-Bissau',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+592',
    uri: require('views/assets/images/flags/gy.png'),
    code: 'GY',
    name: 'Guyana',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+852',
    uri: require('views/assets/images/flags/hk.png'),
    code: 'HK',
    name: 'Hong Kong',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+504',
    uri: require('views/assets/images/flags/hn.png'),
    code: 'HN',
    name: 'Honduras',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+385',
    uri: require('views/assets/images/flags/hr.png'),
    code: 'HR',
    name: 'Croatia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+509',
    uri: require('views/assets/images/flags/ht.png'),
    code: 'HT',
    name: 'Haiti',
    inputMask: '[00] [00] [0000]',
    config: [],
  },
  {
    dialCode: '+36',
    uri: require('views/assets/images/flags/hu.png'),
    code: 'HU',
    name: 'Hungary',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+62',
    uri: require('views/assets/images/flags/id.png'),
    code: 'ID',
    name: 'Indonesia',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+353',
    uri: require('views/assets/images/flags/ie.png'),
    code: 'IE',
    name: 'Ireland',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+972',
    uri: require('views/assets/images/flags/il.png'),
    code: 'IL',
    name: 'Israel',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+91',
    uri: require('views/assets/images/flags/in.png'),
    code: 'IN',
    name: 'India',
    inputMask: '[00000] [00000]',
    config: [],
  },
  {
    dialCode: '+246',
    uri: require('views/assets/images/flags/io.png'),
    code: 'IO',
    name: 'British Indian Ocean Territory',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+964',
    uri: require('views/assets/images/flags/iq.png'),
    code: 'IQ',
    name: 'Iraq',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+98',
    uri: require('views/assets/images/flags/ir.png'),
    code: 'IR',
    name: 'Iran, Islamic Republic of',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+354',
    uri: require('views/assets/images/flags/is.png'),
    code: 'IS',
    name: 'Iceland',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+39',
    uri: require('views/assets/images/flags/it.png'),
    code: 'IT',
    name: 'Italy',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/jm.png'),
    code: 'JM',
    name: 'Jamaica',
    inputMask: '[000] [000] [0000]',
    config: ['876'],
  },
  {
    dialCode: '+962',
    uri: require('views/assets/images/flags/jo.png'),
    code: 'JO',
    name: 'Jordan',
    inputMask: '[0] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+81',
    uri: require('views/assets/images/flags/jp.png'),
    code: 'JP',
    name: 'Japan',
    inputMask: '[00] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+254',
    uri: require('views/assets/images/flags/ke.png'),
    code: 'KE',
    name: 'Kenya',
    inputMask: '[000] [000000]',
    config: [],
  },
  {
    dialCode: '+996',
    uri: require('views/assets/images/flags/kg.png'),
    code: 'KG',
    name: 'Kyrgyzstan',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+855',
    uri: require('views/assets/images/flags/kh.png'),
    code: 'KH',
    name: 'Cambodia',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+686',
    uri: require('views/assets/images/flags/ki.png'),
    code: 'KI',
    name: 'Kiribati',
    inputMask: '[00000000]',
    config: [],
  },
  {
    dialCode: '+269',
    uri: require('views/assets/images/flags/km.png'),
    code: 'KM',
    name: 'Comoros',
    inputMask: '[000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/kn.png'),
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    inputMask: '[000] [000] [0000]',
    config: ['869'],
  },
  {
    dialCode: '+850',
    uri: require('views/assets/images/flags/kp.png'),
    code: 'KP',
    name: "Korea, Democratic People's Republic of",
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+82',
    uri: require('views/assets/images/flags/kr.png'),
    code: 'KR',
    name: 'Korea, Republic of',
    inputMask: '[00] [0000] [0000]',
    config: [],
  },
  {
    dialCode: '+965',
    uri: require('views/assets/images/flags/kw.png'),
    code: 'KW',
    name: 'Kuwait',
    inputMask: '[000] [00000]',
    config: [],
  },
  {
    dialCode: '+7',
    uri: require('views/assets/images/flags/kz.png'),
    code: 'KZ',
    name: 'Kazakhstan',
    inputMask: '[000] [000] [0000]',
    config: [
      '310',
      '311',
      '312',
      '313',
      '315',
      '318',
      '321',
      '324',
      '325',
      '326',
      '327',
      '336',
      '7172',
      '73622',
    ],
  },
  {
    dialCode: '+856',
    uri: require('views/assets/images/flags/la.png'),
    code: 'LA',
    name: "Lao People's Democratic Republic",
    inputMask: '[00] [00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+961',
    uri: require('views/assets/images/flags/lb.png'),
    code: 'LB',
    name: 'Lebanon',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/lc.png'),
    code: 'LC',
    name: 'Saint Lucia',
    inputMask: '[000] [000] [0000]',
    config: ['758'],
  },
  {
    dialCode: '+423',
    uri: require('views/assets/images/flags/li.png'),
    code: 'LI',
    name: 'Liechtenstein',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+94',
    uri: require('views/assets/images/flags/lk.png'),
    code: 'LK',
    name: 'Sri Lanka',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+231',
    uri: require('views/assets/images/flags/lr.png'),
    code: 'LR',
    name: 'Liberia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+266',
    uri: require('views/assets/images/flags/ls.png'),
    code: 'LS',
    name: 'Lesotho',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+370',
    uri: require('views/assets/images/flags/lt.png'),
    code: 'LT',
    name: 'Lithuania',
    inputMask: '[000] [00000]',
    config: [],
  },
  {
    dialCode: '+352',
    uri: require('views/assets/images/flags/lu.png'),
    code: 'LU',
    name: 'Luxembourg',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+371',
    uri: require('views/assets/images/flags/lv.png'),
    code: 'LV',
    name: 'Latvia',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+218',
    uri: require('views/assets/images/flags/ly.png'),
    code: 'LY',
    name: 'Libya',
    inputMask: '[00] [0000000]',
    config: [],
  },
  {
    dialCode: '+212',
    uri: require('views/assets/images/flags/ma.png'),
    code: 'MA',
    name: 'Morocco',
    inputMask: '[000] [000000]',
    config: [],
  },
  {
    dialCode: '+377',
    uri: require('views/assets/images/flags/mc.png'),
    code: 'MC',
    name: 'Monaco',
    inputMask: '[0] [00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+373',
    uri: require('views/assets/images/flags/md.png'),
    code: 'MD',
    name: 'Moldova, Republic of',
    inputMask: '[000] [00] [000]',
    config: [],
  },
  {
    dialCode: '+382',
    uri: require('views/assets/images/flags/me.png'),
    code: 'ME',
    name: 'Montenegro',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+261',
    uri: require('views/assets/images/flags/mg.png'),
    code: 'MG',
    name: 'Madagascar',
    inputMask: '[00] [00] [000] [00]',
    config: [],
  },
  {
    dialCode: '+692',
    uri: require('views/assets/images/flags/mh.png'),
    code: 'MH',
    name: 'Marshall Islands',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+389',
    uri: require('views/assets/images/flags/mk.png'),
    code: 'MK',
    name: 'North Macedonia',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+223',
    uri: require('views/assets/images/flags/ml.png'),
    code: 'ML',
    name: 'Mali',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+95',
    uri: require('views/assets/images/flags/mm.png'),
    code: 'MM',
    name: 'Myanmar',
    inputMask: '[0] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+976',
    uri: require('views/assets/images/flags/mn.png'),
    code: 'MN',
    name: 'Mongolia',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+853',
    uri: require('views/assets/images/flags/mo.png'),
    code: 'MO',
    name: 'Macao',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+596',
    uri: require('views/assets/images/flags/mq.png'),
    code: 'MQ',
    name: 'Martinique',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+222',
    uri: require('views/assets/images/flags/mr.png'),
    code: 'MR',
    name: 'Mauritania',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+356',
    uri: require('views/assets/images/flags/mt.png'),
    code: 'MT',
    name: 'Malta',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+230',
    uri: require('views/assets/images/flags/mu.png'),
    code: 'MU',
    name: 'Mauritius',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+960',
    uri: require('views/assets/images/flags/mv.png'),
    code: 'MV',
    name: 'Maldives',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+265',
    uri: require('views/assets/images/flags/mw.png'),
    code: 'MW',
    name: 'Malawi',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+52',
    uri: require('views/assets/images/flags/mx.png'),
    code: 'MX',
    name: 'Mexico',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+60',
    uri: require('views/assets/images/flags/my.png'),
    code: 'MY',
    name: 'Malaysia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+258',
    uri: require('views/assets/images/flags/mz.png'),
    code: 'MZ',
    name: 'Mozambique',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+264',
    uri: require('views/assets/images/flags/na.png'),
    code: 'NA',
    name: 'Namibia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+687',
    uri: require('views/assets/images/flags/nc.png'),
    code: 'NC',
    name: 'New Caledonia',
    inputMask: '[00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+227',
    uri: require('views/assets/images/flags/ne.png'),
    code: 'NE',
    name: 'Niger',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+234',
    uri: require('views/assets/images/flags/ng.png'),
    code: 'NG',
    name: 'Nigeria',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+505',
    uri: require('views/assets/images/flags/ni.png'),
    code: 'NI',
    name: 'Nicaragua',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+31',
    uri: require('views/assets/images/flags/nl.png'),
    code: 'NL',
    name: 'Netherlands',
    inputMask: '[0] [00000000]',
    config: [],
  },
  {
    dialCode: '+47',
    uri: require('views/assets/images/flags/no.png'),
    code: 'NO',
    name: 'Norway',
    inputMask: '[000] [00] [000]',
    config: [],
  },
  {
    dialCode: '+977',
    uri: require('views/assets/images/flags/np.png'),
    code: 'NP',
    name: 'Nepal',
    inputMask: '[000] [0000000]',
    config: [],
  },
  {
    dialCode: '+674',
    uri: require('views/assets/images/flags/nr.png'),
    code: 'NR',
    name: 'Nauru',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+64',
    uri: require('views/assets/images/flags/nz.png'),
    code: 'NZ',
    name: 'New Zealand',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+968',
    uri: require('views/assets/images/flags/om.png'),
    code: 'OM',
    name: 'Oman',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+507',
    uri: require('views/assets/images/flags/pa.png'),
    code: 'PA',
    name: 'Panama',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+51',
    uri: require('views/assets/images/flags/pe.png'),
    code: 'PE',
    name: 'Peru',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+689',
    uri: require('views/assets/images/flags/pf.png'),
    code: 'PF',
    name: 'French Polynesia',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+675',
    uri: require('views/assets/images/flags/pg.png'),
    code: 'PG',
    name: 'Papua New Guinea',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+63',
    uri: require('views/assets/images/flags/ph.png'),
    code: 'PH',
    name: 'Philippines',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+92',
    uri: require('views/assets/images/flags/pk.png'),
    code: 'PK',
    name: 'Pakistan',
    inputMask: '[000] [0000000]',
    config: [],
  },
  {
    dialCode: '+48',
    uri: require('views/assets/images/flags/pl.png'),
    code: 'PL',
    name: 'Poland',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/pr.png'),
    code: 'PR',
    name: 'Puerto Rico',
    inputMask: '[000] [000] [0000]',
    config: ['787', '939'],
  },
  {
    dialCode: '+970',
    uri: require('views/assets/images/flags/ps.png'),
    code: 'PS',
    name: 'Palestine, State of',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+351',
    uri: require('views/assets/images/flags/pt.png'),
    code: 'PT',
    name: 'Portugal',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+680',
    uri: require('views/assets/images/flags/pw.png'),
    code: 'PW',
    name: 'Palau',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+595',
    uri: require('views/assets/images/flags/py.png'),
    code: 'PY',
    name: 'Paraguay',
    inputMask: '[000] [000000]',
    config: [],
  },
  {
    dialCode: '+974',
    uri: require('views/assets/images/flags/qa.png'),
    code: 'QA',
    name: 'Qatar',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+262',
    uri: require('views/assets/images/flags/re.png'),
    code: 'RE',
    name: 'Réunion',
    inputMask: '[000] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+40',
    uri: require('views/assets/images/flags/ro.png'),
    code: 'RO',
    name: 'Romania',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+381',
    uri: require('views/assets/images/flags/rs.png'),
    code: 'RS',
    name: 'Serbia',
    inputMask: '[00] [0000000]',
    config: [],
  },
  {
    dialCode: '+7',
    uri: require('views/assets/images/flags/ru.png'),
    code: 'RU',
    name: 'Russian Federation',
    inputMask: '[000] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+250',
    uri: require('views/assets/images/flags/rw.png'),
    code: 'RW',
    name: 'Rwanda',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+966',
    uri: require('views/assets/images/flags/sa.png'),
    code: 'SA',
    name: 'Saudi Arabia',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+677',
    uri: require('views/assets/images/flags/sb.png'),
    code: 'SB',
    name: 'Solomon Islands',
    inputMask: '[00] [00000]',
    config: [],
  },
  {
    dialCode: '+248',
    uri: require('views/assets/images/flags/sc.png'),
    code: 'SC',
    name: 'Seychelles',
    inputMask: '[0] [000] [000]',
    config: [],
  },
  {
    dialCode: '+249',
    uri: require('views/assets/images/flags/sd.png'),
    code: 'SD',
    name: 'Sudan',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+46',
    uri: require('views/assets/images/flags/se.png'),
    code: 'SE',
    name: 'Sweden',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+65',
    uri: require('views/assets/images/flags/sg.png'),
    code: 'SG',
    name: 'Singapore',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+386',
    uri: require('views/assets/images/flags/si.png'),
    code: 'SI',
    name: 'Slovenia',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+421',
    uri: require('views/assets/images/flags/sk.png'),
    code: 'SK',
    name: 'Slovakia',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+232',
    uri: require('views/assets/images/flags/sl.png'),
    code: 'SL',
    name: 'Sierra Leone',
    inputMask: '[00] [000000]',
    config: [],
  },
  {
    dialCode: '+378',
    uri: require('views/assets/images/flags/sm.png'),
    code: 'SM',
    name: 'San Marino',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+221',
    uri: require('views/assets/images/flags/sn.png'),
    code: 'SN',
    name: 'Senegal',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+252',
    uri: require('views/assets/images/flags/so.png'),
    code: 'SO',
    name: 'Somalia',
    inputMask: '[0] [0000000]',
    config: [],
  },
  {
    dialCode: '+597',
    uri: require('views/assets/images/flags/sr.png'),
    code: 'SR',
    name: 'Suriname',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+211',
    uri: require('views/assets/images/flags/ss.png'),
    code: 'SS',
    name: 'South Sudan',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+239',
    uri: require('views/assets/images/flags/st.png'),
    code: 'ST',
    name: 'São Tomé and Príncipe',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+503',
    uri: require('views/assets/images/flags/sv.png'),
    code: 'SV',
    name: 'El Salvador',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+963',
    uri: require('views/assets/images/flags/sy.png'),
    code: 'SY',
    name: 'Syrian Arab Republic',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+268',
    uri: require('views/assets/images/flags/sz.png'),
    code: 'SZ',
    name: 'Eswatini',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+235',
    uri: require('views/assets/images/flags/td.png'),
    code: 'TD',
    name: 'Chad',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+228',
    uri: require('views/assets/images/flags/tg.png'),
    code: 'TG',
    name: 'Togo',
    inputMask: '[00] [00] [00] [00]',
    config: [],
  },
  {
    dialCode: '+66',
    uri: require('views/assets/images/flags/th.png'),
    code: 'TH',
    name: 'Thailand',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+992',
    uri: require('views/assets/images/flags/tj.png'),
    code: 'TJ',
    name: 'Tajikistan',
    inputMask: '[000] [00] [0000]',
    config: [],
  },
  {
    dialCode: '+670',
    uri: require('views/assets/images/flags/tl.png'),
    code: 'TL',
    name: 'Timor-Leste',
    inputMask: '[0000] [0000]',
    config: [],
  },
  {
    dialCode: '+993',
    uri: require('views/assets/images/flags/tm.png'),
    code: 'TM',
    name: 'Turkmenistan',
    inputMask: '[00] [000000]',
    config: [],
  },
  {
    dialCode: '+216',
    uri: require('views/assets/images/flags/tn.png'),
    code: 'TN',
    name: 'Tunisia',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+676',
    uri: require('views/assets/images/flags/to.png'),
    code: 'TO',
    name: 'Tonga',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+90',
    uri: require('views/assets/images/flags/tr.png'),
    code: 'TR',
    name: 'Turkey',
    inputMask: '[000] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/tt.png'),
    code: 'TT',
    name: 'Trinidad and Tobago',
    inputMask: '[000] [000] [0000]',
    config: ['868'],
  },
  {
    dialCode: '+688',
    uri: require('views/assets/images/flags/tv.png'),
    code: 'TV',
    name: 'Tuvalu',
    inputMask: '[00] [0000]',
    config: [],
  },
  {
    dialCode: '+886',
    uri: require('views/assets/images/flags/tw.png'),
    code: 'TW',
    name: 'Taiwan, Province of China',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+255',
    uri: require('views/assets/images/flags/tz.png'),
    code: 'TZ',
    name: 'Tanzania, United Republic of',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+380',
    uri: require('views/assets/images/flags/ua.png'),
    code: 'UA',
    name: 'Ukraine',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+256',
    uri: require('views/assets/images/flags/ug.png'),
    code: 'UG',
    name: 'Uganda',
    inputMask: '[000] [000000]',
    config: [],
  },
  {
    dialCode: '+598',
    uri: require('views/assets/images/flags/uy.png'),
    code: 'UY',
    name: 'Uruguay',
    inputMask: '[00] [000] [000]',
    config: [],
  },
  {
    dialCode: '+998',
    uri: require('views/assets/images/flags/uz.png'),
    code: 'UZ',
    name: 'Uzbekistan',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+39',
    uri: require('views/assets/images/flags/va.png'),
    code: 'VA',
    name: 'Holy See (Vatican City)',
    inputMask: '[000] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+1',
    uri: require('views/assets/images/flags/vc.png'),
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    inputMask: '[000] [000] [0000]',
    config: ['784'],
  },
  {
    dialCode: '+58',
    uri: require('views/assets/images/flags/ve.png'),
    code: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    inputMask: '[000] [0000000]',
    config: [],
  },
  {
    dialCode: '+84',
    uri: require('views/assets/images/flags/vn.png'),
    code: 'VN',
    name: 'Vietnam (Việt Nam)',
    inputMask: '[00] [000] [00] [00]',
    config: [],
  },
  {
    dialCode: '+678',
    uri: require('views/assets/images/flags/vu.png'),
    code: 'VU',
    name: 'Vanuatu',
    inputMask: '[000] [0000]',
    config: [],
  },
  {
    dialCode: '+685',
    uri: require('views/assets/images/flags/ws.png'),
    code: 'WS',
    name: 'Samoa',
    inputMask: '[00] [00000]',
    config: [],
  },
  {
    dialCode: '+967',
    uri: require('views/assets/images/flags/ye.png'),
    code: 'YE',
    name: 'Yemen',
    inputMask: '[000] [000] [000]',
    config: [],
  },
  {
    dialCode: '+27',
    uri: require('views/assets/images/flags/za.png'),
    code: 'ZA',
    name: 'South Africa',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
  {
    dialCode: '+260',
    uri: require('views/assets/images/flags/zm.png'),
    code: 'ZM',
    name: 'Zambia',
    inputMask: '[00] [0000000]',
    config: [],
  },
  {
    dialCode: '+263',
    uri: require('views/assets/images/flags/zw.png'),
    code: 'ZW',
    name: 'Zimbabwe',
    inputMask: '[00] [000] [0000]',
    config: [],
  },
];
